name: DependencyTrack for Python/uv

on:
  workflow_call:
    inputs:
      projectName:
        required: true
        type: string
    secrets:
      DEPENDENCYTRACK_APIKEY:
        required: true

jobs:
  dtrack:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get the major version
        id: get_version
        run: echo "MAJOR=${GITHUB_REF/refs\/tags\//}" |cut -d"." -f1 >> "$GITHUB_OUTPUT"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install the project dependencies
        run: poetry install

      - name: Install cyclonedx-bom
        run: pip install cyclonedx-bom

      - name: Generate SBOM
        run: poetry run cyclonedx-py --format json --output sbom.json

      - name: Upload SBOM
        uses: DependencyTrack/gh-upload-sbom@v3
        with:
          serverHostname: 'dependency-track.s1.team'
          protocol: 'https'
          apiKey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          projectName: ${{ inputs.projectName }}
          projectVersion: ${{ steps.get_version.outputs.MAJOR }}
          bomFilename: "sbom.json"
          autoCreate: true
